# go-cqhttp é»˜è®¤é…ç½®æ–‡ä»¶

keywords:
  #- "æ‡‚å“¥"
  #- "å£å£"
  #- "åŠ æƒ"
  #- "éƒ­æ¥ "
  #- "èˆè»"
  #- "ğŸ˜…"

account: # è´¦å·ç›¸å…³
  uin: 1233456 # QQè´¦å·
  password: '' # å¯†ç ä¸ºç©ºæ—¶ä½¿ç”¨æ‰«ç ç™»å½•
  encrypt: false  # æ˜¯å¦å¼€å¯å¯†ç åŠ å¯†
  status: 0      # åœ¨çº¿çŠ¶æ€ è¯·å‚è€ƒ https://docs.go-cqhttp.org/guide/config.html#åœ¨çº¿çŠ¶æ€
  relogin: # é‡è¿è®¾ç½®
    delay: 3   # é¦–æ¬¡é‡è¿å»¶è¿Ÿ, å•ä½ç§’
    interval: 3   # é‡è¿é—´éš”
    max-times: 0  # æœ€å¤§é‡è¿æ¬¡æ•°, 0ä¸ºæ— é™åˆ¶

  # æ˜¯å¦ä½¿ç”¨æœåŠ¡å™¨ä¸‹å‘çš„æ–°åœ°å€è¿›è¡Œé‡è¿
  # æ³¨æ„, æ­¤è®¾ç½®å¯èƒ½å¯¼è‡´åœ¨æµ·å¤–æœåŠ¡å™¨ä¸Šè¿æ¥æƒ…å†µæ›´å·®
  use-sso-address: true

heartbeat:
  # å¿ƒè·³é¢‘ç‡, å•ä½ç§’
  # -1 ä¸ºå…³é—­å¿ƒè·³
  interval: 5

message:
  # ä¸ŠæŠ¥æ•°æ®ç±»å‹
  # å¯é€‰: string,array
  post-format: string
  # æ˜¯å¦å¿½ç•¥æ— æ•ˆçš„CQç , å¦‚æœä¸ºå‡å°†åŸæ ·å‘é€
  ignore-invalid-cqcode: false
  # æ˜¯å¦å¼ºåˆ¶åˆ†ç‰‡å‘é€æ¶ˆæ¯
  # åˆ†ç‰‡å‘é€å°†ä¼šå¸¦æ¥æ›´å¿«çš„é€Ÿåº¦
  # ä½†æ˜¯å…¼å®¹æ€§ä¼šæœ‰äº›é—®é¢˜
  force-fragment: false
  # æ˜¯å¦å°†urlåˆ†ç‰‡å‘é€
  fix-url: false
  # ä¸‹è½½å›¾ç‰‡ç­‰è¯·æ±‚ç½‘ç»œä»£ç†
  proxy-rewrite: ''
  # æ˜¯å¦ä¸ŠæŠ¥è‡ªèº«æ¶ˆæ¯
  report-self-message: false
  # ç§»é™¤æœåŠ¡ç«¯çš„Replyé™„å¸¦çš„At
  remove-reply-at: false
  # ä¸ºReplyé™„åŠ æ›´å¤šä¿¡æ¯
  extra-reply-data: false

output:
  # æ—¥å¿—ç­‰çº§ trace,debug,info,warn,error
  log-level: warn
  # æ˜¯å¦å¯ç”¨ DEBUG
  debug: false # å¼€å¯è°ƒè¯•æ¨¡å¼

# é»˜è®¤ä¸­é—´ä»¶é”šç‚¹
default-middlewares: &default
  # è®¿é—®å¯†é’¥, å¼ºçƒˆæ¨èåœ¨å…¬ç½‘çš„æœåŠ¡å™¨è®¾ç½®
  access-token: ''
  # äº‹ä»¶è¿‡æ»¤å™¨æ–‡ä»¶ç›®å½•
  filter: ''
  # APIé™é€Ÿè®¾ç½®
  # è¯¥è®¾ç½®ä¸ºå…¨å±€ç”Ÿæ•ˆ
  # åŸ cqhttp è™½ç„¶å¯ç”¨äº† rate_limit åç¼€, ä½†æ˜¯åŸºæœ¬æ²¡æ’ä»¶é€‚é…
  # ç›®å‰è¯¥é™é€Ÿè®¾ç½®ä¸ºä»¤ç‰Œæ¡¶ç®—æ³•, è¯·å‚è€ƒ:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # æ˜¯å¦å¯ç”¨é™é€Ÿ
    frequency: 1  # ä»¤ç‰Œå›å¤é¢‘ç‡, å•ä½ç§’
    bucket: 1     # ä»¤ç‰Œæ¡¶å¤§å°

database: # æ•°æ®åº“ç›¸å…³è®¾ç½®
  leveldb:
    # æ˜¯å¦å¯ç”¨å†…ç½®leveldbæ•°æ®åº“
    # å¯ç”¨å°†ä¼šå¢åŠ 10-20MBçš„å†…å­˜å ç”¨å’Œä¸€å®šçš„ç£ç›˜ç©ºé—´
    # å…³é—­å°†æ— æ³•ä½¿ç”¨ æ’¤å› å›å¤ get_msg ç­‰ä¸Šä¸‹æ–‡ç›¸å…³åŠŸèƒ½
    enable: true

# è¿æ¥æœåŠ¡åˆ—è¡¨
servers:
  # æ·»åŠ æ–¹å¼ï¼ŒåŒä¸€è¿æ¥æ–¹å¼å¯æ·»åŠ å¤šä¸ªï¼Œå…·ä½“é…ç½®è¯´æ˜è¯·æŸ¥çœ‹æ–‡æ¡£
  #- http: # http é€šä¿¡
  #- ws:   # æ­£å‘ Websocket
  #- ws-reverse: # åå‘ Websocket
  #- pprof: #æ€§èƒ½åˆ†ææœåŠ¡å™¨
